// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBESnpimyCnDKUNQmX4mlv8z5ekZpVUnJM',
    appId: '1:679260966360:web:3a97faead8c9e8a179f6ad',
    messagingSenderId: '679260966360',
    projectId: 'todoapp-b14f2',
    authDomain: 'todoapp-b14f2.firebaseapp.com',
    storageBucket: 'todoapp-b14f2.firebasestorage.app',
    measurementId: 'G-L21TG9WX93',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvzqVDmymSNqm8ko5Op-QXjdnYEhi_hJw',
    appId: '1:679260966360:android:49fc1f97fad7024779f6ad',
    messagingSenderId: '679260966360',
    projectId: 'todoapp-b14f2',
    storageBucket: 'todoapp-b14f2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHLdip4G30NFjkWPWXRaE-2Zv6-kLZlKk',
    appId: '1:679260966360:ios:8fb46329c8361aea79f6ad',
    messagingSenderId: '679260966360',
    projectId: 'todoapp-b14f2',
    storageBucket: 'todoapp-b14f2.firebasestorage.app',
    iosBundleId: 'com.example.todoapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHLdip4G30NFjkWPWXRaE-2Zv6-kLZlKk',
    appId: '1:679260966360:ios:8fb46329c8361aea79f6ad',
    messagingSenderId: '679260966360',
    projectId: 'todoapp-b14f2',
    storageBucket: 'todoapp-b14f2.firebasestorage.app',
    iosBundleId: 'com.example.todoapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBESnpimyCnDKUNQmX4mlv8z5ekZpVUnJM',
    appId: '1:679260966360:web:7c5959b57368175179f6ad',
    messagingSenderId: '679260966360',
    projectId: 'todoapp-b14f2',
    authDomain: 'todoapp-b14f2.firebaseapp.com',
    storageBucket: 'todoapp-b14f2.firebasestorage.app',
    measurementId: 'G-9CT6HCSTGK',
  );
}
